name: Test reports
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: "hi"
    steps:
      - run: echo "boo" > temp.txt
      - uses: actions/upload-artifact@v2
        with:
          name: temp
          path: temp.txt

