name: Test Launch
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "boo" > temp.txt
      - uses: actions/upload-artifact@v2
        with:
          name: temp.txt
          path: temp.txt
