on:
  pull_request:
    types: [closed]
    branches: 
      - dev
jobs:
  create_release:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --prefix ./.github/actions/create_pr/
      - name: Freshchat Workflow - Pre Release
        id: create_pr
        uses: ./.github/actions/create_pr/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
