on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  create_release:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: npm install --prefix ./.github/actions/create_pr/
      - name: Create PR
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        id: create_pr
        uses: ./.github/actions/create_pr/
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
 
