on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  create_release:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create PR
        id: create_pr
        uses: ./.github/actions/create_pr/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: | 
         npm install
 
