on:
  push:
    branches: 
      - master
      - dev
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: satheeshjm-org/test-actions
          ref: master
          fetch-depth: 1
          token: ${{ github.token }}
          path: test-actions
       
      - name: Install Dependencies
        run: npm install --prefix ./test-actions/actions/gitflow_release/
      
      - name: t
        run: |
          echo ${{ env.GITHUB_REF }}
          echo ${{ env.GITHUB_HEAD_REF }}
          echo ${{ env.GITHUB_BASE_REF }}
          echo ${{ env.GITHUB_SHA }}
        
#      - name: Pre-Release
#        id: pre_release
#        uses: ./test-actions/actions/gitflow_release/
#        with:
#          production_branch: master 
#          staging_branch: dev
#        
#      - name: Release
#        id: create_release
#        uses: ./test-actions/actions/gitflow_release/
#        with:
#          production_branch: master 
#          staging_branch: dev
