env:
  STAGING_BRANCH: dev
  PRODUCTION_BRANCH: master
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASETAG_REGEX: (\d+\.){3}\d+
on:
  pull_request:
    types: 
      - closed
    branches: 
      - dev
      - master
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: satheeshjm-org/test-actions
          ref: master
          fetch-depth: 1
          token: ${{ github.token }}
          path: test-actions
       
     
      - name: Install Stage Dependencies
        if: github.base_ref == env.STAGING_BRANCH
        run: npm install --prefix ./test-actions/actions/gitflow_stage/
      - name: Stage
        id: gitflow_stage
        if: github.base_ref == env.STAGING_BRANCH
        uses: ./test-actions/actions/gitflow_stage/
        with:
          production_branch: ${{ env.PRODUCTION_BRANCH }}
          staging_branch: ${{ env.STAGING_BRANCH }}
          pr_body_config: >
            {
              "table_fields" : 
              [
                {
                "name" : "PR",
                "value": "pr"
                },
                {
                "name" : "OWNER",
                "value": "owner"
                },
                {
                "name": "DDL",
                "value": "file_extension_bool",
                "extension" : "sql"
                }
              ]
            }
       
      - name: Install Release Dependencies
        if: github.base_ref == env.PRODUCTION_BRANCH
        run: npm install --prefix ./test-actions/actions/gitflow_release/
      - name: Release
        id: gitflow_release
        if: github.base_ref == env.PRODUCTION_BRANCH
        uses: ./test-actions/actions/gitflow_release/
        with:
          production_branch: ${{ env.PRODUCTION_BRANCH }} 
          staging_branch: ${{ env.STAGING_BRANCH }}
          releasetag_regex: ${{ env.RELEASETAG_REGEX }}
