env:
  STAGING_BRANCH: dev
  PRODUCTION_BRANCH: master
on:
  pull_request:
    types: 
      - closed
    branches: 
      - ${{ env.STAGING_BRANCH }}
      - ${{ env.PRODUCTION_BRANCH }}
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: satheeshjm-org/test-actions
          ref: master
          fetch-depth: 1
          token: ${{ github.token }}
          path: test-actions
       
      - name: Install Dependencies
        run: npm install --prefix ./test-actions/actions/gitflow_release/
        
      - name: Pre-Release
        id: pre_release
        if: github.base_ref == env.STAGING_BRANCH
        uses: ./test-actions/actions/gitflow_stage/
        with:
          production_branch: master 
          staging_branch: dev
       
      - name: Release
        id: create_release
        if: github.base_ref == env.PRODUCTION_BRANCH
        uses: ./test-actions/actions/gitflow_release/
        with:
          production_branch: master 
          staging_branch: dev
