name: gitflow_stage
env:
  STAGING_BRANCH: dev
  PRODUCTION_BRANCH: master
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: 
      - 'dev'
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: satheeshjm-org/test-actions
          ref: master
          fetch-depth: 1
          token: ${{ github.token }}
          path: test-actions
       
     
      - name: Install Stage Dependencies
        run: npm install --prefix ./test-actions/actions/gitflow_stage/
      - name: Stage
        id: gitflow_stage
        uses: ./test-actions/actions/gitflow_stage/
        with:
          production_branch: ${{ env.PRODUCTION_BRANCH }}
          staging_branch: ${{ env.STAGING_BRANCH }}
          pr_body_config: >
            {
            "table_fields" : 
              [
                { "name" : "PR", "value": "pr"},
                { "name" : "OWNER", "value": "owner"},
                { "name" : "DDL", "value": "does_file_exist", "glob" : "**/*.sql"},
                { "name" : "PROPS", "value": "does_file_contain", "pattern" : "\"\\${[A-Za-z0-9_]+}\""}
              ]
            }
