on:
  pull_request:
    types: 
      - closed
    branches: 
      - master
      - dev
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: satheeshjm-org/test-actions
          ref: master
          fetch-depth: 1
          token: ${{ github.token }}
          path: test-actions
       
      - name: Install Dependencies
        run: npm install --prefix ./test-actions/actions/gitflow_release/
      
      - name: t
        run: |
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo $GITHUB_SHA
        
      - name: Pre-Release
        id: pre_release
        if: $GITHUB_BASE_REF == 'dev'
        uses: ./test-actions/actions/gitflow_stage/
        with:
          production_branch: master 
          staging_branch: dev
       
      - name: Release
        id: create_release
        if: $GITHUB_BASE_REF == 'master'
        uses: ./test-actions/actions/gitflow_release/
        with:
          production_branch: master 
          staging_branch: dev
