on:
  pull_request:
    types: [closed]
    branches: 
      - dev
jobs:
  create_release:
    name: Freshchat Pre Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --prefix ./.github/actions/create_master_pr/
      - name: Create PR to master
        id: create_master_pr
        uses: ./.github/actions/create_master_pr/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
