
name: puppeteer
env:
  PRODUCTION_BRANCH: master
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: 
      - 'dev'
  pull_request:
    types : [labeled] #adding this as a workaround for  triggering action manually
    branches:
      - 'master'
jobs:
  create_release:
    name: Puppeteer Screenshot Action 
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo $npm_config_cache
        env:
          npm_config_cache: ${{ env.PRODUCTION_BRANCH }}
      
      - name: add workspace with echo
        run: echo 'ls $GITHUB_WORKSPACE'

      - name: add workspace with pwd
        run: echo 'pwd'

      - name: Take photo of github.com
        uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
        with:
          url: https://github.com
          width: true
          height: true
          fullPage: true