
name: puppeteer
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: 
      - 'dev'
jobs:
  create_release:
    name: Create Dev To Master PR 
    runs-on: ubuntu-latest
    steps:
     - name: Take photo of github.com
      uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
      with:
        url: https://github.com
        