
# on:
#   pull_request:
#     types: 
#       - closed
#     branches: 
#       - master
on: 
  push:
    branches: 
      - master
jobs:
  create_release:
    name: Freshchat Release Flow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 1
      - name: Cache node modules
        id: cache_node_modules
        uses: actions/cache@v1
        with:
          path: .github/actions/create_release/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.github/actions/create_release/package.json') }}
      - name: ls
        if: steps.cache_node_modules.outputs.cache-hit == 'true'
        run: ls -a .github/actions/create_release/node_modules
      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install --prefix ./.github/actions/create_release/
      - name: ls 
        run: ls -a .github/actions/create_release
      - name: Create Release
        id: create_release
        uses: ./.github/actions/create_release/
        with:
          production_branch: master 
          staging_branch: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
