name: Caching with npm 2

on:
  push:
    branches: 
      - master
      - dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: satheeshjm-org/test-actions
        ref: master
        fetch-depth: 1
        token: ${{ github.token }}
        path: test-actions
    - name: Cache node modules
      id: cache_node_modules
      uses: actions/cache@v1
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('test-actions/actions/gitflow_release/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: ls
      if: steps.cache_node_modules.outputs.cache-hit == 'true'
      run: ls -a ~/.npm
    - name: Install Dependencies
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      run: npm install --prefix test-actions/gitflow_release/
    - name: ls4
      run: ls -a test-actions/gitflow_release/
    - name: ls5
      run: ls -a ~/.npm
